version: '3.9'

services:
  db:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql

    environment:
      MYSQL_ROOT_PASSWORD: password@@
      MYSQL_DATABASE: wordpress
      MYSQL_USER: myuseradmin
      MYSQL_PASSWORD: mypassword!!
    restart: always

  wordpress:
    image: wordpress:latest
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: myuseradmin
      WORDPRESS_DB_PASSWORD: mypassword!!

    volumes:
      - wordpress_data:/var/www/html

    depends_on:
      - db

    ports:
      - "8080:80"
    
    restart: always

volumes:
  mysql_data:
  wordpress_data: