version: '3.9'

services:
  wp:
    image: wordpress:latest
    container_name: wpapp
    volumes:
      - ./wp/web/:/var/www/html/:rw
      - ./logs/:/var/log/:rw
    depends_on:
      - pgdb
    networks:
      - mynet
    ports:
      - "8083:80"
    restart: always

  pgadmin4:
    build:
      context: ./pgadmin
      dockerfile: Dockerfile
    container_name: pgadm4
    depends_on:
      - pgdb
        # - condition: service_healthy
    volumes:
      - ./logs/pgadmin4:/var/log/pgadmin4:rw
    restart: always
    ports:
      - 8081:80
    networks:
      - mynet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -h db"]
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  pgdb:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    container_name: pgresdb
    volumes:
      - ./logs/:/var/log/:rw
      - pg_data_volume:/var/lib/postgresql/data
      - pg_config_volume:/etc/postgresql
      # - pg_logs_volume:/var/log/postgresql 
    networks:
      - mynet
    ports:
      - 5432:5432
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U username -d database_name", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  pg_data_volume:   # Postgres: Data Volume
  pg_config_volume: # Postgres: Configuration Volume
  # pg_logs_volume:   # Postgres: Logs Volume
  logs:
    driver: local
    name: logs

networks:
  mynet:
    driver: bridge